### ISSUE TITLE
SlideUpPanel Error

### ISSUE THREAD

**Issue by nowrobin** [tukcom2022SP/Waiter#135]
MapPage 에 있는  지도 fragment가,  slidepanel 을 올렸다가 하면 제대로 보이는데 처음 화면에서는 짤려서 보입니다. 
xml을 고쳐야되겠습니다.

**Comment by Chynmn** [comment]
넵

**Comment by kyungeunlee07** [comment]
화이팅

**Comment by kyungeunlee07** [comment]
linear layout 마진을 고쳐주면 해결됨
